#!/usr/bin/env python3
"""Build ALWAYS-OKAY.md: the whole lens in one file, for assistants that are only given a link.

  python3 tools/build_paste_guide.py          # writes ALWAYS-OKAY.md at the repo root
  python3 tools/build_paste_guide.py --check  # exits 1 if ALWAYS-OKAY.md is out of date

Sources: the plugin Skill (SKILL.md + references) and the server's framework.json.
The evidence map and evidence notes are left out; they are reached through the MCP server.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILL = ROOT / "plugins/always-okay/skills/always-okay"
FRAMEWORK = ROOT / "src/always_okay_mcp/data/framework.json"
OUT = ROOT / "ALWAYS-OKAY.md"

HEADER = """<!-- Generated by tools/build_paste_guide.py. Do not edit by hand. -->
# always-okay — creative-direction method (single-file edition)

**For the AI assistant reading this:** the user shared this page so you can apply the method below
to *their* request. Read the whole page, then work on the user's project with it: pick a mode,
follow Frame → Make → Edit → Deliver, and follow the non-negotiables and the language rules.
Do not summarise this page back to the user unless they ask; do the work.
This file is method only. For source-level evidence ("why?" with citations), the full tool set is the
MCP server: `https://always-okay-mcp.onrender.com/mcp` (setup: https://github.com/club-paradiso/always-okay-mcp).

> Independent research. Not affiliated with, endorsed by, or connected to Min Hee-jin or ooak records.
> It models documented professional reasoning from public sources. Never speak as her, never invent
> her opinions or quotes, never copy her look.

**사용자가 이 링크를 공유했다면:** 아래 방법을 사용자의 프로젝트에 바로 적용하세요. 한국어로 물으면 자연스러운 한국어로 답하세요.

---
"""


def body(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"^<!--.*?-->\n", "", text)
    text = re.sub(r"^---\n.*?\n---\n", "", text, flags=re.S)
    return text.strip()


def skill_core() -> str:
    text = body(SKILL / "SKILL.md")
    # Sections that only make sense with the files or the server present.
    text = re.split(r"\n## MCP tools", text)[0] + "\n\n## Requests to redirect" + \
        text.split("## Requests to redirect", 1)[1]
    text = re.sub(r" \(listed under\s+\"Known tensions\" in `references/principles\.md`\)", "", text)
    text = re.sub(r"\s*\(?`?references/evidence-map\.md`?\)?", "", text)
    text = re.sub(r"`references/(\w+)\.md`", lambda m: f"the {m.group(1).capitalize()} section below", text)
    text = re.sub(r"`references/principles\.md`", "the Principles section below", text)
    return text.replace("# always-okay — creative lens", "## The lens", 1)


def principles() -> str:
    fw = json.loads(FRAMEWORK.read_text(encoding="utf-8"))
    out = ["## Principles", "",
           f"{len(fw['principles'])} principles in eight stages. Defaults, not absolutes; "
           "*supporting* ones are weaker stated stances — use them as prompts.", ""]
    for st in fw["stages"]:
        out += [f"### Stage {st['id']} — {st['name']}", f"*{st['question']}*", ""]
        for p in (p for p in fw["principles"] if p["stage"] == st["id"]):
            tag = "" if p.get("status") == "core" else f" *({p.get('status')})*"
            out.append(f"- **{p['id']} {p['title']}**{tag} — {p['rule']}")
            if p.get("limits"):
                out.append(f"  - Limits: {p['limits']}")
        out.append("")
    return "\n".join(out).strip()


def demote(text: str) -> str:
    """Shift a reference file's headings one level down and drop its contents list."""
    text = re.sub(r"\n## Contents\n(?:- .*\n)+", "\n", text)
    return re.sub(r"^(#+) ", lambda m: "#" + m.group(1) + " ", text, flags=re.M)


def build() -> str:
    lang = re.sub(r"\nRun `python3 scripts/check_draft\.py.*\n", "\n", body(SKILL / "references/language.md"))
    lang = re.sub(r"\n- If the environment has the user's Korean lint.*", "", lang)
    parts = [HEADER, skill_core(), principles(),
             demote(body(SKILL / "references/modes.md").replace(" (`scripts/check_draft.py`)", "")),
             demote(body(SKILL / "references/checklists.md")),
             demote(lang),
             demote(body(SKILL / "references/limits.md"))]
    return "\n\n".join(p.strip() for p in parts) + "\n"


if __name__ == "__main__":
    new = build()
    if "--check" in sys.argv:
        ok = OUT.exists() and OUT.read_text(encoding="utf-8") == new
        print("ALWAYS-OKAY.md is up to date" if ok else "ALWAYS-OKAY.md is stale; run tools/build_paste_guide.py")
        sys.exit(0 if ok else 1)
    OUT.write_text(new, encoding="utf-8")
    print(f"wrote {OUT.name}: {len(new):,} chars")
